<?php

/**
 * PHP Excel port for EvolutionSDK
 * If the PHP Excel Phar is not already in ./library/
 * the you need to download it from http://phpexcel.codeplex.com/
 */

namespace Bundles\Excel;
use PHPExcel_IOFactory;
use Exception;
use PHPExcel;
use e;

class Bundle {

	public function _on_framework_loaded() {
		e::configure('autoload')->activeAddKey('special', 'PHPExcel', __DIR__ . '/library/PHPExcel.phar');
		e::configure('autoload')->activeAddKey('special', 'PHPExcel_IOFactory', __DIR__ . '/library/PHPExcel.phar');
	}

	public function _on_toExcel($name = 'excel_export', $array = array()) {
		if(empty($array) || empty($array['columns']) || empty($array['rows']))
			throw new Exception("You cannot export an array to excel without columns or rows.");

		// Create new PHPExcel object
		$objPHPExcel = new PHPExcel();

		// Set headers
		$objPHPExcel->getProperties()->setCreator("Excel API")
			->setLastModifiedBy("Excel API")
			->setTitle("Excel API Document")
			->setSubject("Excel API JSON Dump")
			->setDescription("This document was generated by Excel API.")
			->setKeywords("excel dump")
			->setCategory("dump");

		// Create the default sheet
		$sheet = $objPHPExcel->setActiveSheetIndex(0);

		$row_n = 1; $column_n = 'A';
		foreach($array['columns'] as $column) {
			$sheet->setCellValue($column_n.$row_n, $column);
			$column_n++;
		}

		// Bump the row
		$row_n++;

		// Reset the column
		$column_n = 'A';

		// Add data to the excel sheet
		foreach($array['rows'] as $row) {
			foreach($row as $column) {
				$sheet->setCellValue($column_n.$row_n, $column);
				$column_n++;
			}

			$row_n++;
			$column_n = 'A';
		}

		// Set sheet title
		$sheet->setTitle($name);

		// Redirect output to a client’s web browser (Excel2007)
		header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
		header('Content-Disposition: attachment;filename="'.$name.'.xlsx"');
		header('Cache-Control: max-age=0');

		// Save to outout
		$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
		$objWriter->save('php://output');
		
		e\Disable_Trace();
		e\Complete();
	}

}